# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "ui_macroquad"
description = "UI macroquad"
authors = ["Guglielmo Boi"]
version = "1.0.0"
edition = "2021"
exclude = [".*"]

[dependencies]
macroquad = "0.4.4"
robotics_lib = {version = "0.1.21", registry = "kellnr"}
midgard = {version = "0.1.2", registry = "kellnr"}
rust_eze_spotlight = {version = "1.0.0", registry = "kellnr"}
rust_eze_tomtom = {version = "1.0.0", registry = "kellnr"}